---
- hosts: adhoc
  become: true
  become_user: root
  #
  tasks:
  - name: Copy a file
    copy:
#      group: root
#      owner: root
      src: /etc/fstab
      dest: /etc/qumulo_fstab
      remote_src: yes
      mode: 0644
      