---
    ##################################
    # unmount Isilon storage 
    # mount Qumulo stroage 
    # File Net UAT application  
    # wseaman - 2021.06.15 
    ##################################
    #
  - hosts: adhoc.chec.local
    vars:
        mount_src1: qumulo-cr1prd.chec.local:/UAT/USAA
        mount_src2: qumulo-cr1prd.chec.local:/UAT/REV
        mount_src3: qumulo-cr1prd.chec.local:/UAT/FWD   
        mount_path1: /opt/IBM/FileNet/FileStores/UAT/USAA
        mount_path2: /opt/IBM/FileNet/FileStores/UAT/REV
        mount_path3: /opt/IBM/FileNet/FileStores/UAT/FWD

    become: true
    become_user: root

    tasks:
     - name: Unmount usaa
       mount:
        path: /opt/IBM/FileNet/FileStores/UAT/USAA
        state: unmounted

     - name: Unmount reverse
       mount:
        path: /opt/IBM/FileNet/FileStores/UAT/REV
        state: unmounted

     - name: Unmount forward
       mount:
        path: /opt/IBM/FileNet/FileStores/UAT/FWD
        state: unmounted

     - name: check exist qumulo_fstab
       stat: path=/etc/
       register: qumulo_stat

     - name: Move fstab file
       command: mv /etc/qumulo_fstab /etc/fstab
       when: qumulo_stat.stat.exists

     - name: Mount File System USAA
       mount:
         path: "{{ mount_path1 }}"
         src: "{{ mount_src1 }}"
         fstype: nfs
         state: mounted

     - name: Mount File System REV
       mount:
         path: "{{ mount_path2 }}"
         src: "{{ mount_src2 }}"
         fstype: nfs
         state: mounted

     - name: Mount File System FWD
       mount:
         path: "{{ mount_path3 }}"
         src: "{{ mount_src3 }}"
         fstype: nfs
         state: mounted
